/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PureVegRouteImport } from './routes/pure-veg'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as MenuIndexRouteImport } from './routes/menu.index'
import { Route as MenuSectionRouteImport } from './routes/menu.$section'
import { Route as MenuUpwasRouteImport } from './routes/menu.upwas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PureVegRoute = PureVegRouteImport.update({
  id: '/pure-veg',
  path: '/pure-veg',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuSectionRoute = MenuSectionRouteImport.update({
  id: '/menu/$section',
  path: '/menu/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuUpwasRoute = MenuUpwasRouteImport.update({
  id: '/menu/upwas',
  path: '/menu/upwas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pure-veg': typeof PureVegRoute
  '/reserve': typeof ReserveRoute
  '/menu/$section': typeof MenuSectionRoute
  '/menu/upwas': typeof MenuUpwasRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pure-veg': typeof PureVegRoute
  '/reserve': typeof ReserveRoute
  '/menu/$section': typeof MenuSectionRoute
  '/menu/upwas': typeof MenuUpwasRoute
  '/menu': typeof MenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pure-veg': typeof PureVegRoute
  '/reserve': typeof ReserveRoute
  '/menu/$section': typeof MenuSectionRoute
  '/menu/upwas': typeof MenuUpwasRoute
  '/menu/': typeof MenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/pure-veg' | '/reserve' | '/menu/$section' | '/menu/upwas' | '/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/pure-veg' | '/reserve' | '/menu/$section' | '/menu/upwas' | '/menu'
  id:
    | '__root__'
    | '/'
    | '/pure-veg'
    | '/reserve'
    | '/menu/$section'
    | '/menu/upwas'
    | '/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PureVegRoute: typeof PureVegRoute
  ReserveRoute: typeof ReserveRoute
  MenuSectionRoute: typeof MenuSectionRoute
  MenuUpwasRoute: typeof MenuUpwasRoute
  MenuIndexRoute: typeof MenuIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pure-veg': {
      id: '/pure-veg'
      path: '/pure-veg'
      fullPath: '/pure-veg'
      preLoaderRoute: typeof PureVegRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$section': {
      id: '/menu/$section'
      path: '/menu/$section'
      fullPath: '/menu/$section'
      preLoaderRoute: typeof MenuSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/upwas': {
      id: '/menu/upwas'
      path: '/menu/upwas'
      fullPath: '/menu/upwas'
      preLoaderRoute: typeof MenuUpwasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PureVegRoute: PureVegRoute,
  ReserveRoute: ReserveRoute,
  MenuSectionRoute: MenuSectionRoute,
  MenuUpwasRoute: MenuUpwasRoute,
  MenuIndexRoute: MenuIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
